---
  - name: Setup webapp directory
    file:
      path: "{{ webapp_home }}"
      state: directory

  - name: Clone the crewpool repo onto the server
    git:
      repo: "{{ repo_url }}"
      dest: "{{ webapp_home }}"
      version: "master"

  - name: Install pip requirements to virtual env
    pip:
      requirements: "{{ webapp_home }}/requirements.txt"
      virtualenv: "{{ webapp_home }}/env"
      virtualenv_python: python3.6

  - name: Setup logs directory
    file:
      path: "{{ webapp_home }}/logs"
      state: directory
